[project]
name = "excerpts"
version = "0.1.0"
description = "Aggregate and revisit selected texts from books, articles, and other mediums"
readme = "README.md"
authors = [
    { name = "joerisner" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.1",
    "fastapi[standard-no-fastapi-cloud-cli]>=0.141.1",
    "httpx2>=2.12.0",
    "psycopg[binary]>=3.3.4",
    "pwdlib[argon2]>=0.3.1",
    "pyjwt>=2.13.0",
    "sqlalchemy>=2.0.52",
]

[dependency-groups]
dev = [
    "dirty-equals>=0.11",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-env>=1.7.0",
    "ruff>=0.16.5",
    "ty>=0.0.75",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


#################
##### Tools #####
#################

[tool.alembic]
# Using mostly default settings. For additional settings, see:
# https://alembic.sqlalchemy.org/en/latest/tutorial.html#using-pyproject-toml-for-configuration
script_location = "%(here)s/excerpts/alembic" # path to migration scripts
prepend_sys_path = ["."] # additional paths to be prepended to sys.path. defaults to the current working directory.
truncate_slug_length = 40 # max length of characters to apply to the "slug" field
output_encoding = "utf-8" # the output encoding used when revision files are written from script.py.mako
file_template = "%%(year)d%%(month).2d%%(day).2d_%%(hour).2d%%(minute).2d_%%(slug)s" # revision file-naming convention

[tool.coverage.html]
directory = "tests/coverage/html"

[tool.coverage.run]
branch = true
data_file = "tests/coverage/.coverage"
include = ["excerpts/*"]

[tool.coverage.xml]
output = "tests/coverage/coverage.xml"

[tool.fastapi]
entrypoint = "excerpts.main:app"

[tool.pytest.ini_options]
addopts = [
    "--cov",
    "--cov-report=html",
    "--cov-report=xml",
    "--junitxml=tests/test_results/junit.xml",
    "--strict-config",
    "-vv"
]
cache_dir = "tests/.pytest_cache"
junit_suite_name = "excerpts"
pythonpath = ["excerpts"]
testpaths = ["tests"]

[tool.pytest_env]
ECHO_SQL = false
ENVIRONMENT = "test"
POSTGRES_PORT = 5433

[tool.ruff]
line-length = 120

[tool.ruff.format]
docstring-code-format = true
docstring-code-line-length = "dynamic"

[tool.ruff.lint]
select = [
    "F",     # pyflakes
    "E",     # pycodestyle
    "SIM",   # flake8-simplify
    "ARG",   # flake8-unused-arguments
    "PT",    # flake8-pytest-style
    "ANN",   # flake8-annotations
    "S",     # flake8-bandit
    "UP",    # pyupgrade
    "I",     # isort
    "FAST",  # fastapi
    "N"      # pep8-naming
]
ignore = ["ANN401"]  # allow use of `Any` type

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101"  # allow `assert` in tests
]
"excerpts/alembic/versions/*.py" = ["UP"]
