"""add sources table

Revision ID: f3f6238ed8fa
Revises: 50091b373bd3
Create Date: 2026-08-11 00:27:48.452592

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3f6238ed8fa"
down_revision: Union[str, Sequence[str], None] = "50091b373bd3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("cover_image_file", sa.String(length=200), nullable=True),
        sa.Column("type", sa.Enum("article", "book", "essay", "podcast", "video", name="source_type"), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sources_author_id"), "sources", ["author_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sources_author_id"), table_name="sources")
    op.drop_table("sources")
    # ### end Alembic commands ###
