"""add unique constraint to sources table

Revision ID: 6206b625ba64
Revises: afa8eee2f72a
Create Date: 2026-08-15 14:56:24.923623

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6206b625ba64"
down_revision: Union[str, Sequence[str], None] = "afa8eee2f72a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_sources_title_author_id", "sources", ["title", "author_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_sources_title_author_id", "sources", type_="unique")
    # ### end Alembic commands ###
